---
- name: Stop service kafka
  systemd:
    name: kafka
    state: stopped

- name: ' Downloading {{kafka_tgz}} packages'
  become: yes
  become_user: root
  get_url:
    url: '{{kafka_tgz_url}}'
    dest: /tmp/{{kafka_tgz}}
    mode: '0644'
    owner: '{{kafka_user}}'
    group: '{{kafka_group}}'
    timeout: '{{kafka_download_timeout_seconds}}'
#   checksum: '{{kafka_checksum}}'

- name: 'unarchive {{kafka_tgz}} package'
  become: yes
  become_user: root
  unarchive:
  remote_src: yes
  src: /tmp/{{kafka_tgz}}
  dest: '{{kafka_install_dir}}'
  owner: '{{kafka_user}}'
  group: '{{kafka_group}}'

- name: Delete archive...
  become: yes
  become_user: root
  file:
    path: /tmp/{{kafka_tgz}}
    state: absent

- name: unlink..
  shell: unlink '{{kafka_install_parent_dir}}/current'

- name: link..
  shell: ln -s '{{kafka_install_dir}}' '{{kafka_install_parent_dir}}/current'

- template:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    owner: '{{item.user}}'
    group: '{{item.group}}'
  with_items:
    - { src: 'kafka.properties.j2', dest: '{{kafka_properties}}/kafka.properties', user: '{{kafka_user}}', group: '{{kafka_group}}' }



- name: just force systemd to reread configs
  systemd: daemon_reload=yes


- name: started service kafk
  systemd:
    name: kafka
    state: started
